language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  
script: 
  - xctool -workspace Swift_with_the_best_TDD.xcworkspace -scheme 'Swift_with_the_best_TDD' -reporter pretty build-tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  
notifications:
  slack:
    secure: hWf/60xxU1Sw30qZnBbZlhKXZAZAfFARFIV64aFeU9MgxmYpvE0W13UcYny5OHskEjlatdhKS+LIAUaGC0yLGLRKJ9p8Cc1P8XfZ4eUu+iVSpobvyPUU3v4T0jqtb51HH/f3CenaW9slBlAVA7U2RZkqjKsc8+eBQ4fwGQIZeJ2mnE6LWKwkDzYBAvrCOxLo2EcI1UrimLNY7dLeoEq+suN7IYrfFd3y9PVxCQDqOHNYG06mZabYF+zSZYRk1KaZbO2cb2ohx478AYXLEoH+6nBqyAvnTJfKI6RLz6XefRJajrGAVV0tmfcRByl5I5RaZq5GkCvrnd1Rd3XiFOm8IiwTRkT0Cvge4+lpmBZ/9CA75iBkLQcgc4xRidtTaaiHbSg+Pvf8WyHBEK9BHlDDbsuAGF3xPLKYFEu+punWspgdhQ7VFbQiXvq2c/d2mICmrEy5rXS0DVh1RoevkfIzVWQtZMhK9uUkQE1U2essNgGyjmmo5tN4InHOVf80qqyhCkU0/kdcrPRS8oZB80GDmPyTlhE9YiAcvqBPLaACqYuHTBHzJYBHX5VBFG/UhnTrgMyaqgFxsXsOrrz4UkZ/tjWlxwvyVLd75mwH4tTGsRDbq0ZtNRvNP7WuRsbDUvSshL8ENLAfnOLRJR4PU5rgcAHGCr59RAHejXW8Ze+F9+E=


